<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <RootNamespace>Objects.Converter.Revit</RootNamespace>
    <AssemblyName>Objects.Converter.Revit</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autodesk.Revit.SDK" Version="2021.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Core\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\Objects\Objects.csproj" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y /S &quot;$(TargetDir)$(AssemblyName).dll&quot; &quot;$(AppData)\Speckle\Kits\Objects\&quot;" />
  </Target>
</Project>
